### ISSUE TITLE
ワークフローの環境変数が参照できずに異常終了する

### ISSUE THREAD

**Issue by KentaHizume** [AlesInfiny/maia#1119]
# 概要
Marisの下記のissueと同様の問題となります。
- https://github.com/AlesInfiny/maris/issues/1573

openapi-generatorのアップデート確認ワークフローについて、
アップデート要否が非の場合に、envで参照している箇所に値が入っていないことが原因で、
issueの情報を出力するステップが異常終了する。

アップデート要否が非の場合は、該当ステップはスキップされるが、
GitHub Actionsの仕様で、環境変数の評価は行われてしまう。

そのため、&&演算子でチェックを行うように修正する。

```yaml
 STATUS: ${{ steps.create-issue.outputs.outputs && fromJson(steps.create-issue.outputs.outputs).status }}
```
- 該当箇所
```yaml
      - name: issue の情報を出力
        if: ${{ steps.check-version-update.outputs.update-required  == 'true' }}
        env:
          STATUS: ${{ fromJson(steps.create-issue.outputs.outputs).status }}
          ISSUE_NUMBER: ${{ fromJson(steps.create-issue.outputs.outputs).number }}
          ISSUE_URL: ${{ fromJson(steps.create-issue.outputs.outputs).url }}
```

- エラー内容
```terminal
The template is not valid. .github/workflows/check-openapi-generator-update.yml (Line: 79, Col: 19): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/check-openapi-generator-update.yml (Line: 80, Col: 25): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/check-openapi-generator-update.yml (Line: 81, Col: 22): Error reading JToken from JsonReader. Path '', line 0, position 0.
```

# 詳細 / 機能詳細（オプション）
同じ事象が報告されている。

- https://github.com/actions/runner/issues/1722
>Nevertheless, I will mark this as an enhancement and keep it in our backlog, since your proposal does make sense to me to evaluate conditional first and then to skip the entire step if the conditional is false. 
2022/3時点で、実行条件がfalseなら全体をスキップするほうがよいと思うのでバックログに加えておく、
とコメントされているが、特に修正はされていない状態と思われる。

# 完了条件
- [x] アップデート要否が否の場合も正常終了すること
